language: node_js
node_js:
- node
deploy:
  provider: npm
  email: rileyt@ohsu.edu
  skip_cleanup: true
  on:
    tags: true
  api_key:
    secure: uu7kZSAXzh1ix9u6MPfm1ix8i79GMCwhgg6P8SGazcUWFIorsXIxhhd2FDd9vJ02W4Cd/ibBQjPC8RKLrSVX/PM+QwMzhu8/4NdVKcDXR71ykNFk1oRTnypb9jQUymzGpxtGY4mnJalEgoWsw1kt8fhoiVYLXVvMAT0crNGTr6gux82TAULXjqYB/Tv81BO9khc6fNDiOHCUowMJmnT998kANnT139cS22YbQdlxSQTkEI3y9a79sLn642V+xkRoQfEgENoYK8ubOdLpQecimQ6jvMiouKrjky18SXoiCgKUWlbVRTDrq4U9IeYpAIGl2nLXzhfOfPRH7eHf6BoI56gxvadQHOQIYS0GDLYwHbrh9+PiiJVRIv/eVnrLecZQC1F4hq4Nue7ddAepB14uL0tm1GDDVHd06RRGIxmxQyd+DGTwKm8LOqqrGUTQdFLMALREPPEhrkAYrjtqDH66xThFUkBpjWwYO1OhQQF/uglJoKYmZ1vwYeFgObM0i4ey/h4V5ASRQplc23H27g1Q5VJLrjubE3zOKj9Dqgu3emYtTlZLQfclOLQt8kBZndrCPXCaTQ0U/30BMQ2CQJhcnmLjWxybPvFbctNmBj/gPq64p6TBN8DsosbSJ65r7gFex//NRFmFAcugGZJFyzm9569u8VSVlcNBPkgkhYOlKEQ=
