language: node_js
node_js:
- node
deploy:
  provider: npm
  email: jona@ohsu.edu
  skip_cleanup: true
  on:
    tags: true
  api_key:
    secure: FUlfJLZIGXtYoPtvMXAUREs9jz+grjjqqP3xIt+hCyO6zl7Cmr2AzQPnbWFHhmwuqY5qIAXVz0yA0GgMgdlmfqFC1iVuAVpwG/ujOZhzan5/k9TxhMx9LzNAh6QXb6iB1fHI/h0bIvklUpHN2QahwEIZCEd3aMBpiB1nv+hXuFSZo0wvHHfmetm9ixZkeP2IV2PeYjnfYgKv7sQIyklolzkT7cAzjdpKpWPiW36Ng3H6auU9NG02MxEUFvL3aFgrxVkF4EfCHoFCI+7j+JYo0nk15/7HVd56RbiHAFVrlkbBul6eDYr7u8CHydf+830tTcQWOP4rZbzExra8zN4YRxdrXpaVCgnbuP1CWj2w+CMzXFwcXQXumnx+vTCYfd/dWhqO9iray9z41Y1TNG8vN/LsY69YqRv1Fi/4AQJYX1dvzzV6Z+CKDxfI/qrzAwDL7Kq+CYfkadislD8aiOKGQs6nDqB9ae9h4KCx84VOehrGplFkma/ErwD60M/OFyiChq0CRvBWeDXtqweoDCD/W8SFzog/Nic8ReT7Vl1jlH0vPwGKdKR31nTj60AALvoYgbH+goefgX1qdAUaFkdbJyP0WTpUxokK9qOdyGVzYlwZS+xe3WcW4MrVBGMZ8pXq1Oe5ULoh3c+L2SD7VGW/nglVw/pWVp5CjggangNSIP0=
