language: node_js
node_js:
- node
deploy:
  provider: npm
  email: rileyt@ohsu.edu
  skip_cleanup: true
  on:
    tags: true
  api_key:
    secure: VugDteFZWNc0KdZ2StVaHDwPpwu3YV8zepaGrFl8JtRN/B5gvsiaidbjQqIb7rZoKrTlohba7FVGSpB6z0Nq9HcttNO6IBcYO0a1/nX60kpudbQBYsQrPfdllQcGtsEEFPtNLB/FTHsZ/hfFioDHumy5mk6Chn8eVgG5l5FRSeq06CVEZ0vR6mGX5TL15f5I2NiQVv4H0uXx9fyQkHNdfrViEjnvKM3oonhWTOwE+MO0JT5k5Y9MBGPqZBYniL3kYBUH9hr7bhuKymlwplJtj2syUxX76HZIN6thQsCrYUtbvW30uF8CgBWx3pi0svwL0j26pO1Eg9j6UupB9GXWWJgkrSDZnPi5KXomZ9kwYIZ8h0gAbH/bRQYk7lng32pU1CVYVQrtRWjDMkYjYRZtpq/8+1vjy3lqG+AGJTmTX9zAGUn4mkZywX4jJzfmc7hNKcxjQahC+1dl20le36JMZ8KuYYB4m6ZmRQfsGiRCRV590FLxQL/BDsHXjSRlqSjtQs6UX1TdbpQg+ZJBhaUuriQcCvITJMZO7T//dDQBwWmI/ItU+LhKe0F4d3psx2VZyahpu6eJzv57Il+T3b9wJiZSsAm8WFDT2KDHpCRfpi/txKiRceI/wVC/lyOxJdTiLoj75EyCW1Tq8If4qVfAGTv+GVQjWQd81FcNEIfF4Rw=
